apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: santa-claus-game
  namespace: santa
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type"
    nginx.ingress.kubernetes.io/enable-cors: "true"

spec:
  ingressClassName: nginx
  rules:
  - host: santa.apps.g01.containerize.ch
    http:
      paths:
      # Backend API routes
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: santa-backend
            port:
              number: 8080
      # Frontend routes (default)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: santa-claus-game
            port:
              number: 8080